uwigem/uwigem2020-react

package-lock.json
package.json
src/App.js
src/components/_data/HomepageData/HomepageConstants.ts
src/components/common-components/SideBySideComponent/SideBySideComponent.tsx
src/components/common-components/SideBySideComponent/SideBySideStyle.css
src/components/common-components/TwoElementOverlapComponent/TwoElementOverlapComponent.css
src/components/common-components/TwoElementOverlapComponent/TwoElementOverlapComponent.tsx
src/components/footer/footer.js
src/components/home/MainSection/HomepageMainSection.css
src/components/home/MainSection/HomepageMainSection.tsx
src/components/home/home.js
src/components/involve/involve.css
src/components/involve/involve.js
src/components/navbar/navbar.css
src/components/navbar/navbar.js
src/react-app-env.d.ts
tsconfig.json

finish the involvement page design; make minor changes to css because it is hard to achieve image stacking with flexbox

finish get involve page design

---

package-lock.json
package.json
src/components/_data/HomepageData/HomepageConstants.ts
src/components/common-components/SideBySideComponent/SideBySideComponent.tsx
src/components/common-components/SideBySideComponent/SideBySideStyle.css
src/components/common-components/TwoElementOverlapComponent/TwoElementOverlapComponent.css
src/components/common-components/TwoElementOverlapComponent/TwoElementOverlapComponent.tsx
src/components/home/MainSection/HomepageMainSection.css
src/components/home/MainSection/HomepageMainSection.tsx
src/components/home/home.js

Main section completed with overlapping elements component.
No typography CSS has been added because I'm assuming it will be centralized for the entire website

Homepage First Section Complete

---

src/components/home/home.js
src/components/join-us/JoinUs.module.css
src/components/join-us/JoinUs.tsx
src/components/join-us/SocialMediaLink.module.css
src/components/join-us/SocialMediaLink.tsx

Join us part complete with animations

---

src/components/common-components/TwoElementOverlapComponent/TwoElementOverlapComponent.css
src/components/common-components/TwoElementOverlapComponent/TwoElementOverlapComponent.tsx

Might not even use this component with all the complicated math but here it is anyway

Two component overlap patch

---

src/components/common-components/SideBySideComponent/SideBySideComponent.tsx
src/components/common-components/SideBySideComponent/SideBySideStyle.css
src/components/home/MainSection/HomepageMainSection.css
src/components/home/MainSection/HomepageMainSection.module.css
src/components/home/MainSection/HomepageMainSection.tsx
src/components/home/competition/competition.module.css
src/components/home/competition/competition.tsx
src/components/home/home.js

This might have some conflicts because I edited the side by side component to make more sense

Homepage competition

---

src/components/common-components/SlidingDoors/SlidingDoors.module.css
src/components/common-components/SlidingDoors/SlidingDoors.tsx
src/components/join-us/JoinUs.module.css
src/components/join-us/JoinUs.tsx
src/components/join-us/SocialMediaLinks.tsx
src/components/join-us/linksData.tsx

When the join us component is visible on screen, the animation will progress depending on how much of it is on the screen.

Join-Us component's Scrolling animation

---

src/App.js
src/components/team/OurTeamPage.css
src/components/team/OurTeamPage.js
src/components/team/teamOverview/teamOverview.css
src/components/team/teamOverview/teamOverview.js
src/components/team/teamPage.css
src/components/team/teamPage.js
src/components/team/teamStructure/teamInfo.css
src/components/team/teamStructure/teamInfo.js
src/components/team/teamStructure/teamStatement.css
src/components/team/teamStructure/teamStatement.js
src/components/team/teamStructure/teamStructure.css
src/components/team/teamStructure/teamStructure.js

- Add team structure component
- Add team overview component
- Add "Our team" page
- Leave some space for the sidebar to come in (Note to Victor: if you are writing the sidebar, feel free to replace those inline CSS with your code. Those are just placeholders)
Feel free to test around with the two components (overview & structure).

Diana team structure & team overview component

---

src/App.js
src/components/navbar/navbar.js
src/components/team/TeamPageMembers.js
src/components/team/TeamPageTeam.js
src/components/team/teamPage.css

Edit team button color and heading style

---

src/components/common-components/ProjectBlock/ProjectBlock.js

@VictorShan thank you for pointing the bugs out! 
The hovering effect bug should be fixed now.

turn cursor to pointer when hover + fix pop-up hovering effect bug

---

src/components/team/TeamPageSideBar.css
src/components/team/TeamPageSideBar.js

Teampage sidebar

---

src/components/team/TeamPageSideBar.css

added correct minwidth for sidebar

---

src/components/common-components/SlidingDoors/SlidingDoors.module.css

Solves join us links being unclickable

set sliding doors to clickthrough

---

package-lock.json
package.json
src/components/team/TeamPageTeam.js
src/components/team/gallery/gallery.css
src/components/team/gallery/gallery.js

- Add team gallery section on team page

add team gallery section

---

src/components/involve/Fundraising/Fundraising.css
src/components/involve/Fundraising/Fundraising.js
src/components/involve/SynbioForEveryone/SynbioForEveryone.css
src/components/involve/SynbioForEveryone/SynbioForEveryone.js

- making the title on the involvement page responsive sizing

make involvement text responsive

---

src/components/team/membersPage/Members.js
src/components/team/membersPage/Members.module.css
src/components/team/membersPage/fadeStyle.module.css

Filtering on members page doesn't lead to jumping around

Smooth filter

---

src/components/involve/Recruitment/RecruitTeamInfo.css
src/components/involve/Recruitment/RecruitTeamInfo.tsx
src/components/involve/Recruitment/RecruitTeamPosition.tsx
src/components/involve/Recruitment/RecruitTeamPostion.css
src/components/involve/Recruitment/RecruitmentMenu.css
src/components/involve/Recruitment/RecruitmentMenu.tsx
src/components/involve/involve.js

Add the recruitment section
- similar to the team structure menu we have on "Team" page

add recruitment section

---

src/components/archive/archive.json

Diana fill text

---

src/components/involve/involve.js
src/components/team/membersPage/Members.js

fixes switching two times between members and team

fix unmounting error

---

.gitignore
package-lock.json
package.json
src/components/home/Popup/FirstTimePopup.tsx
src/components/home/home.js
src/components/join-us/JoinUs.tsx
src/components/team/TeamPageMembers.tsx
src/components/team/TeamPageTeam.tsx
tsconfig.json

Add popup for first time visitors

---

src/components/involve/Recruitment/RecruitmentManagerInfo.css
src/components/involve/Recruitment/RecruitmentManagerInfo.tsx
src/components/involve/Recruitment/RecruitmentMenu.tsx

Added managers section to Get Involved Page

Jaden managers
